### ISSUE TITLE
Cache packages

### ISSUE THREAD

**Issue by andrewgodman** [jandelgado/lede-dockerbuilder#15]
Hi, I know this is might be an issue with LEDE/Openwrt's build tools but each build requires a download of every package.

I'd love to provide a solution but I wasn't able to find one without some sort of http proxy.

**Comment by andrewgodman** [comment]
I was able to do this by adding the following variable to the docker file and running a proxy. Maybe this isn't such an issue but downloads can take 5 mins for a simple build in Australia.

`ENV http_proxy "http://host.docker.internal:8080"`

Would be interested in anyone else who might have feedback :)

**Comment by jandelgado** [comment]
Hi, in fact, the OpenWRT packages are currently not cached and re-loaded each time a new OpenWRT image is built. I did some quick experiments and there are 2 easy options to cache the packages:

* use an external caching proxy (e.g. squid) and set `http_proxy` variables in container
* mount `/dl` as an external docker volume so that package downloads survive individual buillds

I'll come up with conrcrete examples later this weekend ...

**Comment by andrewgodman** [comment]
@jandelgado sounds good. Squid works well but I might see if I can mount /dl as a volume.

**Comment by jandelgado** [comment]
Release 2.4 allows to pass additional options to docker-run. This can be used to mount the downloads (`dl`) directory externally:
```
./builder.sh build example-nexx-wt3020.conf --docker-opts "-v=$(pwd)/dl:/lede/imagebuilder/dl:z"
```
See #18

**Comment by andrewgodman** [comment]
I'll check it out. My internet was finally upgraded so it may be less of an issue for me.
